version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^Merge'
  groups:
    - title: 'Features'
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: 'Performance'
      regexp: '^perf(\(.+\))?:'
      order: 2
    - title: 'Documentation'
      regexp: '^docs(\(.+\))?:'
      order: 3
    - title: 'Refactoring'
      regexp: '^refactor(\(.+\))?:'
      order: 4
    - title: 'Tests'
      regexp: '^test(\(.+\))?:'
      order: 5
    - title: 'Build'
      regexp: '^build(\(.+\))?:'
      order: 6
    - title: 'CI'
      regexp: '^ci(\(.+\))?:'
      order: 7
    - title: 'Chores'
      regexp: '^chore(\(.+\))?:'
      order: 8

release:
  github:
    owner: sirsjg
    name: gogo
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - repository:
      owner: sirsjg
      name: homebrew-gogo
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    name: gogo
    homepage: "https://github.com/sirsjg/gogo"
    description: "Streaming LLM CLI with multi-provider support"
    license: "MIT"
    test: |
      system "#{bin}/gogo", "-v"
    install: |
      bin.install "gogo"
